var data = {
    "211 cm": "Giraffe",
    "208 cm": "Ostrich",
    "188 cm": "Horse",
    "185 cm": "Gorilla",
    "183 cm": "White Rhino",
    "180 cm": "Giant River Otter (standing)",
    "178 cm": "Llama",
    "175 cm": "Wild Water Buffalo",
    "173 cm": "Eastern Gorilla",
    "170 cm": "Black Bear (standing)",
    "168 cm": "Emu",
    "165 cm": "Hippo",
    "163 cm": "Grévy's Zebra",
    "160 cm": "Giant Panda (standing)",
    "157 cm": "Reindeer",

    "155 cm": "Greater Kudu Antelope",

    "152 cm": "Elk",

    "150 cm": "Red Kangaroo",
    "149 cm": "",
    "148 cm": "",
    "147 cm": "",
    "146 cm": "",
    "145 cm": "",
    "144 cm": "",
    "143 cm": "",
    "142 cm": "",
    "141 cm": "",
    "140 cm": "",
    "139 cm": "",
    "138 cm": "",
    "137 cm": "",
    "136 cm": "",
    "135 cm": "",
    "134 cm": "",
    "133 cm": "",
    "132 cm": "",
    "131 cm": "",
    "130 cm": "",
    "129 cm": "",
    "128 cm": "",
    "127 cm": "",
    "126 cm": "",
    "125 cm": "",
    "124 cm": "",
    "123 cm": "",
    "122 cm": "",
    "121 cm": "",
    "120 cm": "",
    "119cm": "Greater Flamingo",
    "118cm": "Greater Flamingo",
    "117cm": "Greater Flamingo",
    "116cm": "Greater Flamingo",
    "115cm": "Greater Flamingo",
    "114cm": "Greater Flamingo",
    "113cm": "Greater Flamingo",
    "112cm": "Greater Flamingo",
    "111cm": "Greater Flamingo",
    "110cm": "Greater Flamingo",
    "109cm": "",
    "108cm": "",
    "107cm": "",
    "106cm": "",
    "105cm": "",
    "104cm": "",
    "103cm": "",
    "102cm": "",
    "101cm": "",
    "100cm": "Bengal Tiger",
    "99cm": "Bengal Tiger",
    "98cm": "Bengal Tiger",
    "97cm": "Bengal Tiger",
    "96cm": "Bengal Tiger",
    "95cm": "Bengal Tiger",
    "94cm": "Bengal Tiger",
    "93cm": "Bengal Tiger",
    "92cm": "Bengal Tiger",
    "91cm": "Bengal Tiger",
    "90cm": "Giant Panda",
    "89cm": "Giant Panda",
    "88cm": "Giant Panda",
    "87cm": "Giant Panda",
    "86cm": "Giant Panda",
    "85cm": "Giant Panda",
    "84cm": "Giant Panda",
    "83cm": "Giant Panda",
    "82cm": "Giant Panda",
    "81cm": "Giant Panda",
    "80cm": "Bald Eagle",
    "79cm": "Bald Eagle",
    "78cm": "Bald Eagle",
    "77cm": "Bald Eagle",
    "76cm": "Bald Eagle",
    "75cm": "Bald Eagle",
    "74cm": "Bald Eagle",
    "73cm": "Bald Eagle",
    "72cm": "Bald Eagle",  
    "71cm": "Thomson's gazelle",
    "70cm": "Thomson's gazelle",
    "69cm": "Thomson's gazelle",
    "68cm": "Thomson's gazelle",
    "67cm": "Thomson's gazelle",
    "66cm": "Thomson's gazelle",
    "65cm": "Northern Brown Kiwi",
    "64cm": "Northern Brown Kiwi",
    "63cm": "Northern Brown Kiwi",
    "62cm": "Northern Brown Kiwi",
    "61cm": "Northern Brown Kiwi",
    "60cm": "Northern Brown Kiwi",
    "59cm": "Northern Brown Kiwi",
    "58cm": "Nigerian Dwarf Goat",
    "57cm": "Nigerian Dwarf Goat",
    "56cm": "Nigerian Dwarf Goat",
    "55cm": "Nigerian Dwarf Goat",
    "54cm": "Nigerian Dwarf Goat",
    "53cm": "Nigerian Dwarf Goat",
    "52cm": "Adélie Penguin",
    "51cm": "Adélie Penguin",
    "50cm": "Adélie Penguin",
    "49cm": "Adélie Penguin",
    "48cm": "Adélie Penguin",
    "47cm": "Beaver",
    "46cm": "Beaver",
    "45cm": "Beaver",
    "44cm": "Beaver",
    "43cm": "Beaver",
    "42cm": "Red Fox",
    "41cm": "Red Fox",
    "40cm": "Red Fox",
    "39cm": "Red Fox",
    "38cm": "Red Fox",
    "37cm": "Red Fox",
    "36cm": "Red Fox",
    "35cm": "Red Fox",
    "34cm": "Red Panda",
    "33cm": "Red Panda",
    "32cm": "Red Panda",
    "31cm": "Red Panda",
    "30cm": "Red Panda",
    "29cm": "Red Panda",
    "28cm": "Red Panda",
    "27cm": "House Cat",
    "26cm": "House Cat",
    "25cm": "House Cat",
    "24cm": "House Cat",
    "23cm": "House Cat",
    "22cm": "American Mink",
    "21cm": "American Mink",
    "20cm": "American Mink",
    "19cm": "American Mink",
    "18cm": "American Mink",
    "17cm": "Platypus ",
    "16cm": "Platypus ",
    "15cm": "Platypus ",
    "14cm": "Platypus ",
    "13cm": "Platypus ",
    "12cm": "Platypus ",
    "11cm": "Common Rat",
    "10cm": "Common Rat",
    "9cm": "Common Rat",
    "8cm": "Green Frog",
    "7cm": "Green Frog",
    "6cm": "Amazon Milk Frog",
    "5cm": "Amazon Milk Frog",
    "4cm": "Amazon Milk Frog",
    "3cm": "Hog-nosed Bat",
    "2cm": "Hog-nosed Bat",
    "1cm": "Tiny Little Guy!"
};
