// Referenced data from https://www.dimensions.com/browse/animals?6c3303e6_page=2

var data = {
    "212 cm": "Giraffe????? who are you???",
    "211 cm": "Moose",
    "210 cm": "Moose",
    "209 cm": "Moose",
    "208 cm": "Moose",
    "207 cm": "Moose",
    "206 cm": "Moose",
    "205 cm": "Moose",
    "204 cm": "Ostrich",
    "203 cm": "Ostrich",
    "202 cm": "Ostrich",
    "201 cm": "Ostrich",
    "200 cm": "Ostrich",
    "199 cm": "Ostrich",
    "198 cm": "European Bison",
    "197 cm": "European Bison",
    "196 cm": "European Bison",
    "195 cm": "European Bison",
    "194 cm": "European Bison",
    "193 cm": "European Bison",
    "192 cm": "European Bison",
    "191 cm": "Okapi",
    "190 cm": "Okapi",
    "189 cm": "Okapi",
    "188 cm": "Okapi",
    "187 cm": "Okapi",
    "186 cm": "Okapi",
    "185 cm": "Okapi",
    "184 cm": "Okapi",
    "183 cm": "White Rhino",
    "182 cm": "White Rhino",
    "181 cm": "White Rhino",
    "180 cm": "White Rhino ",
    "179 cm": "White Rhino ",
    "178 cm": "White Rhino ",
    "177 cm": "Llama",
    "176 cm": "Llama",
    "175 cm": "Llama",
    "174 cm": "Llama",
    "173 cm": "Black Wildebeest",
    "172 cm": "Black Wildebeest",
    "171 cm": "Black Wildebeest",
    "170 cm": "Black Wildebeest",
    "169 cm": "Mountain Gorilla",
    "168 cm": "Mountain Gorilla",
    "167 cm": "Mountain Gorilla",
    "166 cm": "Mountain Gorilla",
    "165 cm": "Black Bear (standing)",
    "164 cm": "Black Bear (standing)",
    "163 cm": "Black Bear (standing)",
    "162 cm": "Black Bear (standing)",
    "161 cm": "Bighorn Sheep",
    "160 cm": "Bighorn Sheep",
    "159 cm": "Bighorn Sheep",
    "158 cm": "Bighorn Sheep",
    "157 cm": "Bighorn Sheep",
    "156 cm": "Plains Zebra",
    "155 cm": "Plains Zebra",
    "154 cm": "Plains Zebra",
    "153 cm": "Plains Zebra",
    "152 cm": "Plains Zebra",
    "151 cm": "Red Kangaroo",
    "150 cm": "Red Kangaroo",
    "149 cm": "Red Kangaroo",
    "148 cm": "Red Kangaroo",
    "147 cm": "Red Kangaroo",
    "146 cm": "Hippopotamus",
    "145 cm": "Hippopotamus",
    "144 cm": "Hippopotamus ",
    "143 cm": "Hippopotamus ",
    "142 cm": "Hippopotamus ",
    "141 cm": "Hippopotamus ",
    "140 cm": "Hippopotamus",
    "139 cm": "Reindeer",
    "138 cm": "Reindeer",
    "137 cm": "Reindeer",
    "136 cm": "Reindeer",
    "135 cm": "Reindeer",
    "134 cm": "Reindeer",
    "133 cm": "Domestic Yak",
    "132 cm": "Domestic Yak",
    "131 cm": "Domestic Yak",
    "130 cm": "Domestic Yak",
    "129 cm": "Domestic Yak",
    "128 cm": "Domestic Yak",
    "127 cm": "Sumatran Orangutan",
    "126 cm": "Sumatran Orangutan",
    "125 cm": "Sumatran Orangutan",
    "124 cm": "Sumatran Orangutan",
    "123 cm": "Sumatran Orangutan",
    "122 cm": "Sumatran Orangutan",
    "121 cm": "Sumatran Orangutan",
    "120 cm": "Sumatran Orangutan",
    "119 cm": "Greater Flamingo",
    "118 cm": "Greater Flamingo",
    "117 cm": "Greater Flamingo",
    "116 cm": "Greater Flamingo",
    "115 cm": "Greater Flamingo",
    "114 cm": "Greater Flamingo",
    "113 cm": "Greater Flamingo",
    "112 cm": "Greater Flamingo",
    "111 cm": "Greater Flamingo",
    "110 cm": "Greater Flamingo",
    "109 cm": "Alpaca",
    "108 cm": "Alpaca",
    "107 cm": "Alpaca",
    "106 cm": "Alpaca",
    "105 cm": "Alpaca",
    "104 cm": "Alpaca",
    "103 cm": "Alpaca",
    "102 cm": "Alpaca",
    "101 cm": "Alpaca",
    "100 cm": "Bengal Tiger",
    "99 cm": "Bengal Tiger",
    "98 cm": "Bengal Tiger",
    "97 cm": "Bengal Tiger",
    "96 cm": "Bengal Tiger",
    "95 cm": "Bengal Tiger",
    "94 cm": "Bengal Tiger",
    "93 cm": "Bengal Tiger",
    "92 cm": "Bengal Tiger",
    "91 cm": "Bengal Tiger",
    "90 cm": "Giant Panda",
    "89 cm": "Giant Panda",
    "88 cm": "Giant Panda",
    "87 cm": "Giant Panda",
    "86 cm": "Giant Panda",
    "85 cm": "Giant Panda",
    "84 cm": "Giant Panda",
    "83 cm": "Giant Panda",
    "82 cm": "Giant Panda",
    "81 cm": "Giant Panda",
    "80 cm": "Bald Eagle",
    "79 cm": "Bald Eagle",
    "78 cm": "Bald Eagle",
    "77 cm": "Bald Eagle",
    "76 cm": "Bald Eagle",
    "75 cm": "Bald Eagle",
    "74 cm": "Bald Eagle",
    "73 cm": "Bald Eagle",
    "72 cm": "Bald Eagle",
    "71 cm": "Thomson's gazelle",
    "70 cm": "Thomson's gazelle",
    "69 cm": "Thomson's gazelle",
    "68 cm": "Thomson's gazelle",
    "67 cm": "Thomson's gazelle",
    "66 cm": "Thomson's gazelle",
    "65 cm": "Northern Brown Kiwi",
    "64 cm": "Northern Brown Kiwi",
    "63 cm": "Northern Brown Kiwi",
    "62 cm": "Northern Brown Kiwi",
    "61 cm": "Northern Brown Kiwi",
    "60 cm": "Northern Brown Kiwi",
    "59 cm": "Capybara",
    "58 cm": "Capybara",
    "57 cm": "Capybara",
    "56 cm": "Capybara",
    "55 cm": "Capybara",
    "54 cm": "Capybara",
    "53 cm": "Capybara",
    "52 cm": "Adélie Penguin",
    "51 cm": "Adélie Penguin",
    "50 cm": "Adélie Penguin",
    "49 cm": "Adélie Penguin",
    "48 cm": "Adélie Penguin",
    "47 cm": "Beaver",
    "46 cm": "Beaver",
    "45 cm": "Beaver",
    "44 cm": "Beaver",
    "43 cm": "Beaver",
    "42 cm": "Red Fox",
    "41 cm": "Red Fox",
    "40 cm": "Red Fox",
    "39 cm": "Red Fox",
    "38 cm": "Red Fox",
    "37 cm": "Red Fox",
    "36 cm": "Red Fox",
    "35 cm": "Red Fox",
    "34 cm": "Red Panda",
    "33 cm": "Red Panda",
    "32 cm": "Red Panda",
    "31 cm": "Red Panda",
    "30 cm": "Red Panda",
    "29 cm": "Red Panda",
    "28 cm": "Red Panda",
    "27 cm": "House Cat",
    "26 cm": "House Cat",
    "25 cm": "House Cat",
    "24 cm": "House Cat",
    "23 cm": "House Cat",
    "22 cm": "American Mink",
    "21 cm": "American Mink",
    "20 cm": "American Mink",
    "19 cm": "American Mink",
    "18 cm": "American Mink",
    "17 cm": "Platypus",
    "16 cm": "Platypus",
    "15 cm": "Platypus",
    "14 cm": "Platypus",
    "13 cm": "Platypus",
    "12 cm": "Platypus",
    "11 cm": "Common Rat",
    "10 cm": "Common Rat",
    "9 cm": "Common Rat",
    "8 cm": "Green Frog",
    "7 cm": "Green Frog",
    "6 cm": "Amazon Milk Frog",
    "5 cm": "Amazon Milk Frog",
    "4 cm": "Amazon Milk Frog",
    "3 cm": "Hog-nosed Bat",
    "2 cm": "Hog-nosed Bat",
    "1 cm": "Literal bug"
};
